CREATE OR REPLACE FUNCTION ADD_ALBUM(NEW_ALBUM VARCHAR(128))
RETURNS boolean
AS
$$
BEGIN
  IF EXISTS (SELECT FROM album a WHERE a.name = NEW_ALBUM) THEN
    RETURN FALSE;
  ELSE
    INSERT INTO album (name)
    VALUES (NEW_ALBUM);
    RETURN TRUE;
  END IF;
END;
$$ LANGUAGE plpgsql;