
CREATE OR REPLACE FUNCTION ADD_STOCK(ALBUM VARCHAR(128), AMOUNT INT )

RETURNS boolean
AS
$$
DECLARE albumId INT;

BEGIN
  IF EXISTS (SELECT id INTO albumId FROM album a WHERE a.name = ALBUM ) THEN

    INSERT INTO album_stock VALUES (DEFAULT,albumId, AMOUNT);
    RETURN TRUE;
  ELSE
    RETURN FALSE;
  END IF;
END;
$$ LANGUAGE plpgsql;
