CREATE OR REPLACE FUNCTION DURATION_TO_STRING(SEGONDE INT)
RETURNS VARCHAR(10)
AS
$$

DECLARE 
resultat  VARCHAR(10);
minute INT := SEGONDE / 60;
reste  INT := SEGONDE % 60;

BEGIN
    IF SEGONDE <= 0 THEN
        SET resultat =  '00:00';
        RETURN resultat;
    END IF;

    IF SEGONDE >0 THEN

        SELECT CONCAT(CAST(ROUND(SEGONDE / 60 ) AS CHAR(4)), ':' , CAST( (ROUND(SEGONDE%60))  AS CHAR(4))) INTO resultat;
        RETURN resultat;
    END IF;
END;

$$ LANGUAGE plpgsql;

SELECT  DURATION_TO_STRING(1008);
SELECT  DURATION_TO_STRING(8);
SELECT  DURATION_TO_STRING(6008);